[tool.poetry]
name = "locator"
version = "0.1.0"
description = ""
authors = ["HighCasMan <borody.rula@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
