name: Auto tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip3 install -r requirements.txt
      - name: Run Locator
        run: python manage.py runserver 127.0.0.1:8080
      - name: Run tests
        run: pytest
